### ISSUE TITLE
有点不会用

### ISSUE THREAD

**Issue by shmilyty** [MelodyYuuka/nonebot_plugin_everyday_en#1]
在群聊里直接使用的时候出现报错
- 已经安装了软依赖
![image](https://user-images.githubusercontent.com/61276699/160425413-ba9f4568-bf8c-4486-8612-2de7f01e50b7.png)
不知道是不是因为安装原插件的时候出现了warning的原因，具体报错如下：
![image](https://user-images.githubusercontent.com/61276699/160425319-41a2668d-d6fc-47fb-85c1-f2936441fc72.png)
![image](https://user-images.githubusercontent.com/61276699/160425568-809dd21e-549d-4cc8-a306-f06190c22486.png)
![image](https://user-images.githubusercontent.com/61276699/160425606-17f71662-037e-43ae-9eca-fb10cb1555ce.png)
在http端也有相应的报错：
![image](https://user-images.githubusercontent.com/61276699/160425896-0ce99379-dc36-41f1-8b85-c9e51a96f257.png)

**Comment by MelodyYuuka** [comment]
你没有安装FFmpeg，你可以自行下载并添加进环境变量，参考 https://docs.go-cqhttp.org/guide/quick_start.html#安装-ffmpeg .
