### ISSUE TITLE
有关插件私聊触发的问题

### ISSUE THREAD

**Issue by bugcatcapoo** [MelodyYuuka/nonebot_plugin_everyday_en#2]
不知道为什么，现在SU似乎无法在私聊的情况下对机器人的该插件进行执行和修改~~以前似乎是可以的~~

![image](https://user-images.githubusercontent.com/104308239/166147366-2c27f32d-a170-45bc-83e0-cc5675dca0c6.png)

![image](https://user-images.githubusercontent.com/104308239/166147378-82c2d4de-93f4-474c-a834-4919bc4a2195.png)

**Comment by MelodyYuuka** [comment]
发一下私聊时的后台日志

**Comment by bugcatcapoo** [comment]
不好意思，最近忙于应付月考，没有及时回复
![image](https://user-images.githubusercontent.com/104308239/167251785-608a568c-8249-4b4f-860e-84af3e86319d.png)

**Comment by MelodyYuuka** [comment]
看起来你这个就没触发成功啊，
检查一下插件是否正常加载。
这边本地测试是成功触发的，
另外查看列表的命令是"查看定时每日一句列表"。

**Comment by MelodyYuuka** [comment]
长时间无响应就先close了，随时可以reopen

**Comment by bugcatcapoo** [comment]
我不好说
我刚刚重新卸载安装了一遍该插件，然后确保正确配置了（但愿如此）
![image](https://user-images.githubusercontent.com/104308239/170270039-02ac1cd3-30eb-4ec1-a796-81f652ad88f8.png)
![image](https://user-images.githubusercontent.com/104308239/170270075-83321558-e507-4958-be47-39592aeae92a.png)
![image](https://user-images.githubusercontent.com/104308239/170270135-fe10b4b5-7821-4617-96d3-fe71d79c9cff.png)
现在貌似只有私聊功能用不了（不管对方是否是superuser），群聊自动发送是可以正常使用的
有没有一种可能，下载的代码不是最新的
[\_\_init__.py](https://paste.ubuntu.com/p/BNRbf4MTj4/)

**Comment by MelodyYuuka** [comment]
目测可能是某些插件的matcher设置了block=True或block参数缺省
这边全版本测试均可用，包括pip上的1.1.5，请用debug等级打印日志，在你所使用的env文件内设置LOG_LEVEL=DEBUG。

**Comment by bugcatcapoo** [comment]
我刚刚把 `Nonebot Plugin Manager` 的加载关掉了，重启了一次，似乎还是不成功
![image](https://user-images.githubusercontent.com/104308239/170498189-fbc0acf8-aad1-4fd7-b5dc-a756086b8360.png)

**Comment by MelodyYuuka** [comment]
你的 ``nonebot_plugin_hentai`` 插件的 matcher 设置了 block=True ，其 priority 优先于本插件的 matcher ，触发后则 stop 了事件传播，以致本插件的 matcher 不能触发，请停用该插件或手动修改该插件的matcher参数 block=False

**Comment by bugcatcapoo** [comment]
成功了，谢谢您
