### ISSUE TITLE
报错：AsyncClient.get() got an unexpected keyword argument 'follow_redirects'

### ISSUE THREAD

**Issue by nyanshu** [MelodyYuuka/nonebot_plugin_everyday_en#3]
出现如下报错
![image](https://user-images.githubusercontent.com/109270234/194556791-0a27e0c4-5f7e-4729-be30-ed69e7e3f503.png)

**Comment by MelodyYuuka** [comment]
提供一下python版本和httpx的版本

**Comment by nyanshu** [comment]
python 3.10
httpx 0.19.0

**Comment by MelodyYuuka** [comment]
尝试更新httpx到最新版本

**Comment by nyanshu** [comment]
更新httpx后问题解决，感谢大佬
